FROM node:22

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

# Build the production bundle
RUN npm run build

# Keep container running so nginx can access the dist folder
CMD ["tail", "-f", "/dev/null"]
