services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    working_dir: /app
    depends_on:
      - backend
    networks:
      - appnet
    volumes:
      - ./frontend:/app # bind mount
      - frontend_node_modules:/app/node_modules
      - ./shared:/shared
      - ./backend/certs:/app/certs

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    working_dir: /app
    networks:
      - appnet
    volumes:
      - ./backend:/app # bind mount
      - backend_node_modules:/app/node_modules
      - ./shared:/app/shared
      - ./backend/prisma/database:/app/prisma/database # bind mount
      - ./backend/certs:/app/certs
    environment:
      - FORCE_COLOR=1 # add color to terminal output
      - HTTPS_ENABLED=true

volumes:
  frontend_node_modules:
  backend_node_modules:

networks:
  appnet:
    driver: bridge
