services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    working_dir: /app
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - appnet
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./backend/room.db:/app/room.db
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
